### ISSUE TITLE
red/green color blindness

### ISSUE THREAD

**Issue by earosenthal** [spsanderson/healthyR.ai#219]
I noticed that you used red/green on your PCA loadings and variance explained plots. About 8% of the male population has red/green color blindness. I recommend that you use colors that are easier to distinguish. Here is one example that could help: https://cran.r-project.org/web/packages/colorBlindness/vignettes/colorBlindness.html

**Comment by spsanderson** [comment]
https://stackoverflow.com/questions/19300134/ggplot2-with-colour-blind-ggthemes-except-black
