### ISSUE TITLE
Using compatibility `.name_repair`.

### ISSUE THREAD

**Issue by VladPerervenko** [spsanderson/healthyR.ai#319]
> ump_lst <- hai_umap_list(.data = uit_tbl, kmm_tbl, 3)
Joining with `by = join_by(service_line)`
Warning message:
The `x` argument of `as_tibble.matrix()` must have unique column names if `.name_repair` is omitted as of tibble
2.0.0.
ℹ Using compatibility `.name_repair`.
ℹ The deprecated feature was likely used in the healthyR.ai package.
  Please report the issue at <https://github.com/spsanderson/healthyR.ai/issues>.

**Comment by spsanderson** [comment]
Fixed and will be included in the new release.
